### PR TITLE
Translated into Spanish

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jgibbon** [comment]
Awesome, thank you so much!

Two small notes I hope you can address before I integrate your changes: 
- (I know this is missing in the english file as well, sorry.) You can correctly use "numerus" forms (so it's possible to output  "open one file" and "open 2 files" instead of "open 1 file(s)") by either using a gui tool like qt linguist (it's pretty easy to use – and free!) to create your translations or just adding two <numerusform> tags like in [the german translation example](https://github.com/jgibbon/Talefish/blob/f9cf23b25804adddd0c98959cbeb2b440605a7a9/translations/Talefish-de.ts#L23).
The first tag represents singular, the second one plural.
- The TS-Tag needs a language attribute – [this](https://github.com/jgibbon/Talefish/blob/3fe734e14863c202887f6ac7e9c978cc8b8a5ec9/translations/Talefish-es.ts#L3) should be` <TS language="es" version="2.1">`, I think. 

Again, thank you!

**Comment by ghost** [comment]
HI velox
- TS-Tag======= FIXED i guess
- Numerus forms= FIXED i guess

**Comment by jgibbon** [comment]
Hi, no problem, we all have to start somewhere.
The TS-Tag is exactly right. 


For the numerus it has do be:
```xml
<translation>
<numerusform>[output if the placeholder %1 inside is 1]</numerusform>
<numerusform>[output if the placeholder %1 inside is bigger than 1]</numerusform>
</translation>
```

You currently have:
```xml
<translation>
Click en el archivo para abrirlo o aceptar el diálogo para abrir %1 fichero(s)
<numerusform></numerusform>
Click en el archivo para abrirlo o aceptar el diálogo para abrir %1 fichero(s)</numerusform></translation>
```

It's almost right, but the texts have to be between `<numerusform>` and `</numerusform>`, for example (this will be horribly wrong spanish, my apologies):

```xml
<translation>
<numerusform>Click en el archivo para abrirlo o aceptar el diálogo para abrir una fichero</numerusform>
<numerusform>Click en el archivo para abrirlo o aceptar el diálogo para abrir %1 ficheros</numerusform>
</translation>
```

edit: messed up a bit myself there…

**Comment by ghost** [comment]
ok i will fix it right now , i am confused  following your the german translation example. en first line.

**Comment by jgibbon** [comment]
I'll merge the pull request and try to fix the rest after it – you'll see what was changed then.
Thanks, again, for your work!

(If you need to edit some translations, you can then edit the file with qt linguist instead of a text editor – it takes care of all that XML syntax stuff.)

**Comment by jgibbon** [comment]
I've fixed the other stuff at https://github.com/jgibbon/Talefish/commit/4cd0e907911198023e276670af8934635c409497

**Comment by jgibbon** [comment]
Oh, by the way, there are new strings available for translation. I've added those in the Talefish-es.ts in https://github.com/jgibbon/Talefish/commit/707857446ed449774f3d24e009c94ea21e592b8e :)

**Pull request merged**
