### PR TITLE
Increased range for playbackRate

### PR DESCRIPTION
**Pull request by thigg**

### CODE REVIEW

**Comment by jgibbon** [comment]
Hi @thigg,
thank you for taking the time to seep through the sources to find the place for this change.
I haven't yet come across audio books where a range this big would be useful, but… well, it doesn't hurt much. Except for making it a bit more difficult to set the desired speed acurately.

So I might as well just merge it.
cheers,
velox


Related and fixed with this: #16

**Comment by thigg** [comment]
thanks!
I guess it depends on the audiobook and your habits.
The worst drawback I see, is that without pitch compensation you get an... interesting... listening experience.

**Comment by jgibbon** [comment]
Exactly, which I was a bit against that in the linked issue #16 – but not heavily enough to resist someone else doing it, apparently.
It would be interesting to check if [Audiocut](https://openrepos.net/content/planetos/audiocut) is a viable option to change a files speed – I haven't had the time to do that. If that had pitch correction, that could be really useful.

cheers!

**Comment by thigg** [comment]
Good suggestion. Going to take a look into Audiocut

**Comment by thigg** [comment]
Took a look into audiocut, its using ffmpeg to do stuff with audiofiles.

Using some try and error, i got decent audio using:

`ffmpeg -i input.mp3 -filter:a "atempo=2.0"  -f wav  pipe:1  | paplay --raw`

Maybe we can build on that.
I will try to build a drop-in replacement for the QMediaPlayer which is based on ffmpeg

**Pull request merged**
