### PR TITLE
Update Talefish-es.ts

### PR DESCRIPTION
**Pull request by ghost**
smallers tranlations added

### CODE REVIEW

**Comment by jgibbon** [comment]
Yeah! Thank you so much!

**Comment by jgibbon** [comment]
Oh, I just noticed someone else started helping to translate in spanish on Transifex. Would you be willing to use that service in the future? This way the work won't be done twice, because everyone would see the work already finished instantly…
https://www.transifex.com/velocode/talefish/

**Comment by ghost** [comment]
I already know that carmenfb began to help translate, I really do not like transifex to translate.
Maybe she was interested in helping to translate because the translation I did in Talefish for Spanish made a series of errors, so I did an update to fix the whole bunch of errors from a preliminary point of view including adjusting the word strings On margin passes. Then it is very important to release the next version to reflect all the corrections.

**Comment by jgibbon** [comment]
I've tried to merge them as best as I could for the new build…

**Pull request merged**
