### PR TITLE
Update Talefish-es.ts

### PR DESCRIPTION
**Pull request by ghost**
Lots of fixes and optimization

### CODE REVIEW

**Comment by ghost** [comment]
captura_20170126_001
 -Also @jgibbon you have problems in layout in long pressing line. it too big phrase, you can fix delete 3-4 words on the pharase. I FIXED IN MY IDIOM I GUESS in the translation.     
-Also below the screenshot you see a word in English and that I could not translate because I did not find those words in the letter to translate. Can you add those words to translate?

GOOD DAY  ;  )

**Comment by jgibbon** [comment]
Thanks! I've added an extra text in the options to make the lines smaller and fix the layout problems. Also added an option for "do nothing" on button press…

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
repaired

**Comment by jgibbon** [comment]
Thank you very much for your work!

**Pull request merged**
