### PR TITLE
Update AboutPage.qml

### PR DESCRIPTION
**Pull request by carlosgonz0**
refactoring

### CODE REVIEW

**Comment by jgibbon** [comment]
Removing thanks without any explanation is not "refactoring", it is wasting everyone's time.

**Comment by jgibbon** [comment]
Wait. That was you? Why was your name only in the notification mail and is different here? Please explain, I may reopen this.

**Comment by carlosgonz0** [comment]
caballlero was my first nickname, later was changed to carlosgonz, so i am the both names, but i am fine that carmenfdez is showed by main spanish translator in Talefish. :  )

**Comment by carlosgonz0** [comment]
i was the first person interested in translate to spanish Talefish i did huge work on it, later carmenfdez did a translation of transiflex by modifying on my work in Talefish, so that is why i am ok that carmenfdez being as spanish translator, i am totally ok.

**Comment by jgibbon** [comment]
Okay, I'll remove your nick as per your wish. But be assured that your hard work still is appreciated even if some of it was built upon by others. Thank you!

**Pull request merged**
