### PR TITLE
made sure, playbackspeed is always set when audio starts

### LINKED ISSUE #33: playback speed not always set
1. Set playback speed != 1
2. audio plays faster.
3. wait until track changes
IS: after track change, playback speed jumps back to 1
SHOULD: keep the set playback speed

and 

1. Have playback speed != 1
2. Close app
3. start app
4. start audio
IS: playback speed back to 1
SHOULD: keep the set playback speed

Background is that the QtMediaPlayer of Sailfish gets pitch compensation when playback speed is changed:
https://forum.sailfishos.org/t/no-pitch-compensation-when-playing-audio-with-playbackrate-1/

### PR DESCRIPTION
**Pull request by thigg**
fixes #33

### CODE REVIEW

**Comment by jgibbon** [comment]
Wow, I wasn't aware pitch correction seems to be coming, that is awesome! I've tried numerous times to implement pitch correction from inside the app but nothing worked to my satisfaction.

Also I actually thought that I tested playback speed with the previous rework of the player. 
Thanks for all your efforts ([including qtmultimedia](https://forum.sailfishos.org/t/no-pitch-compensation-when-playing-audio-with-playbackrate-1/1369/14)), I'm really stoked and can barely wait for the first SFOS release to include this!

The change in this PR seems to make sense, but I'll have some time testing it (and making a new release) in the next days or next weekend, even if it's just those two lines setting the speed plus the nicer equality check.

**Comment by jgibbon** [comment]
Sadly, this does have some problems I didn't catch while having a first look:
 - Doing `playbackRate = app.options.playbackRate` loses the change binding on the options – so changing the options afterwards doesn't have an effect anymore until restarting the application.
 - The `if` in which you set it first only gets executed when the option to automatically play the next file in the playlist is set to `false`, so basically when pausing after a track.
 - `playbackRate` in itself is already set, there is "just" a bug somewhere (perhaps only because it's an ancient qt?) that it doesn't work most of the time – I've found that on some occasions a seek is necessary to make it work. Just setting `playbackRate` again does not have an effect. At least on the unpatched version of qtmultimedia shipped with SFOS. 

I'm really curious if your changes worked in the patched qtmultimedia you seem to have installed…

A possible workaround (seeking to somewhere close to the current position, sadly sometimes resulting in some stutter) kind of works when used after `seekableChanged` (and after setting a new `playbackSpeed` in the options). I'll have to test a bit more to possibly reduce the side effects (and with a few more file types), but I may include something like that again soon-ish. (I had that workaround at some point but could have sworn it worked after one upgrade.) I'd then love to remove that workaround (again) should it not be necessary anymore in the future.

Nevertheless, thank you very much for taking the time and effort to make me aware of this and trying to fix it.

**Comment by thigg** [comment]
Yes I already noticed that its not working perfectly. I agree that this is most likely a bug in QT. Maybe we can report a bug for this on the forum if we can pin it down.

**Comment by jgibbon** [comment]
Issue is now handled by the 'seek workaround' in 0.7-1 (on openrepos for now).
Thanks again!

**Pull request closed without merging**
